name: namer_app
description: A new Flutter project.

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Ensure compatibility within the specified range

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  intl: ^0.17.0  # Adjust to match the latest version compatible with your SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
